name: HRNet Env
on:
 push:
   branches:
     - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
    - uses: actions/checkout@v2
    - name: Publish Image
      uses: matootie/github-docker@v3.0.0
      with:
        accessToken: ${{ secrets.TOKEN }}
        tag: |
          latest
          ${{github.sha}}
        imageName: simple-hrnet
